#!/usr/bin/env bash
#
# macOS Homebrew installer
#

set -euo pipefail

echo "==> Installing Homebrew packages for macOS..."

# Install Homebrew if not present
if ! command -v brew &>/dev/null; then
  echo "==> Installing Homebrew..."
  /bin/bash -c \
    "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

brew update --force # https://github.com/Homebrew/brew/issues/1151

echo "==> Installing packages via Homebrew Bundle..."
brew bundle --file=- <<EOF
  brew "the_silver_searcher"
  brew "neovim"
  brew "zsh"
  brew "tmux"
  cask "iterm2"

  brew "koekeishiya/formulae/skhd"
  brew "koekeishiya/formulae/yabai"

  brew "gh"
  brew "thefuck"
  brew "cmatrix"

  brew "postgresql@14", restart_service: :changed
  brew "redis", restart_service: :changed

  brew "crystal"
  tap "luckyframework/homebrew-lucky"
  brew "lucky"
  brew "yarn"
EOF

# Install Oh-My-Zsh
if [[ ! -d "${HOME}/.oh-my-zsh" ]]; then
  echo "==> Installing Oh-My-Zsh..."
  git clone https://github.com/ohmyzsh/ohmyzsh.git "${HOME}/.oh-my-zsh" || \
    git clone git@github.com:ohmyzsh/ohmyzsh.git "${HOME}/.oh-my-zsh"
fi

# Install ASDF
if [[ ! -d "${HOME}/.asdf" ]]; then
  echo "==> Installing ASDF..."
  git clone https://github.com/asdf-vm/asdf.git "${HOME}/.asdf"
fi

add_or_update_asdf_plugin() {
  local name="$1"
  local url="$2"

  if ! asdf plugin-list | grep -Fq "$name"; then
    asdf plugin-add "$name" "$url"
  else
    asdf plugin-update "$name"
  fi
}

# shellcheck source=/dev/null
source "${HOME}/.asdf/asdf.sh"
add_or_update_asdf_plugin "ruby" "https://github.com/asdf-vm/asdf-ruby.git"
add_or_update_asdf_plugin "nodejs" "https://github.com/asdf-vm/asdf-nodejs.git"

install_asdf_language() {
  local language="$1"
  local version
  version="$(asdf list-all "$language" | grep -v "[a-z]" | tail -1)"

  if ! asdf list "$language" | grep -Fq "$version"; then
    asdf install "$language" "$version"
    asdf global "$language" "$version"
  fi
}

echo "==> Installing Ruby via ASDF..."
install_asdf_language "ruby"
gem update --system
number_of_cores=$(sysctl -n hw.ncpu)
bundle config --global jobs $((number_of_cores - 1))

echo "==> Installing Node.js via ASDF..."
install_asdf_language "nodejs"

echo "==> macOS installation complete!"
