FROM archlinux:latest

RUN pacman -Syy --needed --noconfirm sudo

RUN useradd --create-home najawa
RUN echo "najawa ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

COPY . /home/najawa/.dotfiles
WORKDIR /home/najawa/.dotfiles
RUN chown -R najawa:najawa .

USER najawa

RUN mkdir $HOME/.ssh

RUN ./install

CMD /bin/zsh
